# Generated by Django 5.0.6 on 2024-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('book', 'Livre'), ('article', 'Article')], default='book', max_length=20),
        ),
    ]
