# Generated by Django 5.0.6 on 2024-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
